title: Web-to-Print
email: cschmidt@cca.edu, jsueda@cca.edu
description: "A course about browser exploration at California College of the Arts in the Fall of 2017"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://web-to-print.doing.computer" # the base hostname & protocol for your site
github_username: web-to-print
